### ISSUE TITLE
Implement saturating growth

### ISSUE THREAD

**Issue by MBrouns** [MBrouns/timeseers#2]

**Comment by kori73** [comment]
I would like to work on this issue if it's still relevant. I think this can be done with some adjustments to the linear trend. gamma is defined recursively for the saturating growth, so I am thinking of using two `theano.scan` loops. The first loop iterates over each series, and the second one does the recursive updating.

**Comment by MBrouns** [comment]
Hiya! It's definitely still relevant, and it would be awesome if you want to take a stab at it. Do you need me to run you through some of the internals before you can start?

**Comment by kori73** [comment]
Thanks a lot for asking. I think I am going okay for now. But I can ask some help on one issue. I am not really sure how to deal with the cap. I am going for something like this:

```
model = SaturatingGrowth(n_changepoints=10)
model.fit(df[["t", "cap"]], df["y"], tune=2000)
```
The problem is now the cap is transformed with `X_scaler`. But it seems like cap should be transformed with `y_scaler`.

Another problem is that when we call the `plot_components`, daily `t` is generated with a `lookahead_scale `. However, we also need pass the cap for all `t`. Somehow the user should be able to pass the future values of cap. I might be missing some existing functionality though.

For now I am using a hardcoded cap that works for the data I use just to get a working model. After that, I will have to deal with the cap.

**Comment by MBrouns** [comment]
That's a good point, and indeed it's something that's not well supported yet. I ran into the same issue with implementing the additional regressors. 

I have an idea on how the API for this should look, but haven't gotten around to implementing it yet. For now, I'd say it's fine to use a fixed hardcoded capacity.
